spring.application.name=mediqueue

# Database
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/mediqueue_db}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Done@123}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=${PORT:8080}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoCo